modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="obfuscate"
version="0.4.1"
displayName="Obfuscate"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/Obfuscate/master/update.json"
displayURL="https://mrcrayfish.com/"
logoFile="obfuscate.png"
credits="Cheers to these people for donating during the development: Fabbe50, Infinite Worlds, ALBERT, Mastef Chief, OstenTV, Robert Finley, PlayDashGaming, Shadow Bill-cat"
authors="MrCrayfish"
description="A simple library that adds in useful events"

[[dependencies.obfuscate]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.obfuscate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"